In [1]:
import pandas as pd
import numpy as np
import altair as alt
import seaborn as sns
from pybliometrics import scopus
from main import Corpus
import Bibliography_Parse
import geopandas as gpd
import matplotlib.pyplot as plt
import gpdvega
import multiprocessing
from geopy.geocoders import Photon
color_dict={'Astrobiology': '#2FD03D', 'Bioastronautics': '#3D2FD0', 'Space Bioprocess Engineering': '#D03D2F'}
color_dict_2={'AB': '#2FD03D', 'BA': '#3D2FD0', 'SBE': '#D03D2F'}

alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('gpd_to_values')

In [2]:
author_ids = pd.read_csv('unique_authors')['0']
author_ids

0         8397364800
1        36664765600
2        35177423100
3         7005325946
4         7409615288
            ...
49718    57215592822
49719     8424066900
49720     8706064700
49721     8644474800
49722    55584445800
Name: 0, Length: 49723, dtype: int64

In [3]:
bioscience_bibliography = pd.read_csv('bioscience_bibliography')
bioscience_bibliography.author_ids = bioscience_bibliography.author_ids.str.split(';')
bioscience_bibliography.author_afids = bioscience_bibliography.author_afids.str.split(';')
bioscience_bibliography.afid = bioscience_bibliography.afid.str.split(';')
bioscience_bibliography = bioscience_bibliography[['author_ids', 'author_afids', 'afid']]
# bioscience_bibliography.author_afids.apply(lambda x: len(x) if type(x)==list else 1)
bioscience_bibliography

,author_ids,author_afids,afid
0,"[56993931000, 54974731000, 58153269000, 700494...","[60027272, 60012708-124841290, 129393708, 6002...","[60170182, 60072546, 60031581, 60027272, 60014..."
1,"[56487197100, 58146986100, 6507732731, 1360595...","[60028039, 60136210-60073837, 60028039, 60028039]","[60136210, 60073837, 60028039]"
2,"[57222579646, 57211144665, 57192302909, 222342...","[60019616, 60019616, 60030637, 60019616, 60019...","[60030637, 60019616, 60001439, 60000481]"
3,[7102359712],[60007202-113582880],"[60007202, 113582880]"
4,"[57212383059, 57218845028, 57278545200, 571915...","[121595840-60011976, 121595840, 121595840, 121...","[60011976, 128131936, 121595840, 115293926]"
...,...,...,...
24784,[35520941200],NaN,NaN
24785,NaN,NaN,NaN
24786,[7404152751],NaN,NaN
24787,[6508021729],NaN,NaN
24788,[55691605600],[60001262],[60001262]

In [77]:
# scopus.AffiliationRetrieval(110785288)._profile['@parent']

# pd.DataFrame(scopus.AffiliationSearch('af-id(110785288)').affiliations)

# scopus.AffiliationRetrieval(113587821).affiliation_name
# scopus.AffiliationRetrieval(113587821).self_link

dict_keys(['@affiliation-id', 'status', 'date-created', 'preferred-name', 'sort-name', 'name-variant', 'address'])

In [7]:
def to_1D(series):
    flattened = []
    for element in series:
        if isinstance(element, list):
            flattened.extend(element)
        elif isinstance(element, np.ndarray):
            flattened.extend(element.tolist())
    return pd.Series(flattened)


set(to_1D(bioscience_bibliography.afid))

{'60000088',
 '113075111',
 '60114739',
 '60020990',
 '60015615',
 '60072836',
 '60020321',
 '60112425',
 '60072236',
 '60020096',
 '60004814',
 '60007183',
 '60007103',
 '60003079',
 '60072296',
 '60025352',
 '60022286',
 '60178602',
 '128987739',
 '126274105',
 '100319158',
 '60012162',
 '60012689',
 '110685232',
 '60028925',
 '60017252',
 '60019359',
 '60005384',
 '60101299',
 '60030426',
 '60011733',
 '60156343',
 '100818130',
 '60021323',
 '60085627',
 '60020730',
 '60017681',
 '112884793',
 '60033165',
 '118445492',
 '114402415',
 '60103895',
 '60006404',
 '60021542',
 '60000765',
 '108418597',
 '60003531',
 '60139009',
 '60008724',
 '60174564',
 '60008208',
 '106639316',
 '60025884',
 '60077572',
 '60002445',
 '60072960',
 '60024878',
 '60003970',
 '121573339',
 '118496271',
 '123196386',
 '60012771',
 '125190635',
 '60032499',
 '107103023',
 '107572501',
 '119562782',
 '60030364',
 '60030114',
 '100341857',
 '118747359',
 '121099540',
 '60032895',
 '60070029',
 '60005634',
 '124841290',
 '60121644',
 '60019442',
 '101525477',
 '126983701',
 '129008162',
 '100601208',
 '60024582',
 '60029526',
 '60010071',
 '60103639',
 '60078901',
 '60016755',
 '60005269',
 '60023662',
 '101522739',
 '125374245',
 '60017150',
 '60006838',
 '60016425',
 '60023403',
 '60027085',
 '124131547',
 '109703335',
 '101776943',
 '114520824',
 '118430927',
 '60020124',
 '114615036',
 '101128169',
 '126398112',
 '120288924',
 '60014200',
 '60122781',
 '60028229',
 '60005085',
 '60000294',
 '100355022',
 '122203387',
 '60012556',
 '100548525',
 '60031591',
 '113950963',
 '60024421',
 '114865574',
 '112773828',
 '60013404',
 '60014653',
 '60012383',
 '60004893',
 '100721553',
 '109666609',
 '100406874',
 '113320885',
 '118691418',
 '120697026',
 '113925720',
 '122379498',
 '60082715',
 '102081708',
 '60012256',
 '60084247',
 '60000931',
 '60011614',
 '60023833',
 '60138680',
 '60013083',
 '60024295',
 '60029700',
 '60002316',
 '60102054',
 '60209951',
 '60011561',
 '60002210',
 '60096651',
 '123988319',
 '118387659',
 '60011340',
 '60033147',
 '60073428',
 '60030657',
 '60015324',
 '60122052',
 '60006832',
 '60003548',
 '60006940',
 '60015827',
 '60083539',
 '114682332',
 '60030992',
 '60011374',
 '60031620',
 '60012621',
 '60031533',
 '114204093',
 '125281338',
 '60009000',
 '128283670',
 '60022653',
 '109973845',
 '113768549',
 '60014416',
 '109599444',
 '60021334',
 '60015339',
 '101011961',
 '60016247',
 '60091990',
 '60021918',
 '60117289',
 '100536946',
 '60031117',
 '60020261',
 '60014801',
 '60113612',
 '60108490',
 '120290752',
 '60107169',
 '60016114',
 '60021564',
 '60020416',
 '60018984',
 '122508380',
 '106595422',
 '112348506',
 '60010896',
 '60027837',
 '100637783',
 '60018600',
 '60072567',
 '60025157',
 '119080323',
 '60106662',
 '100412138',
 '60023197',
 '60069080',
 '114599773',
 '60032114',
 '60012553',
 '114292710',
 '109669839',
 '110078522',
 '60027093',
 '100728232',
 '60033291',
 '60004686',
 '60012797',
 '60017294',
 '60012769',
 '100346135',
 '60096349',
 '60007247',
 '60023317',
 '60094843',
 '60020661',
 '60009963',
 '127915062',
 '60070475',
 '60027950',
 '117369724',
 '60121568',
 '60011003',
 '101555528',
 '109621580',
 '60005273',
 '60032493',
 '60274668',
 '125778801',
 '117252030',
 '60027136',
 '60009415',
 '60109750',
 '112900484',
 '60021028',
 '122507155',
 '113125294',
 '60016728',
 '60107041',
 '100391733',
 '113704821',
 '60024693',
 '60009226',
 '60000521',
 '60088268',
 '123196460',
 '112867261',
 '60025286',
 '60001096',
 '60015138',
 '113582875',
 '60116086',
 '60021615',
 '106380350',
 '60031546',
 '118063278',
 '60004584',
 '60204338',
 '123151925',
 '109887162',
 '100750047',
 '60078563',
 '60022919',
 '60121356',
 '60005558',
 '101651495',
 '116424122',
 '60010495',
 '101652174',
 '60012944',
 '115129988',
 '60008981',
 '125540098',
 '60016329',
 '100595685',
 '60004745',
 '60108524',
 '121322529',
 '122328280',
 '60031115',
 '100913904',
 '60001490',
 '60008588',
 '60032215',
 '60106053',
 '100815003',
 '60275530',
 '60099651',
 '106959556',
 '60121547',
 '60006225',
 '100580164',
 '107182936',
 '60157975',
 '60093602',
 '60007870',
 '125208907',
 '60027428',
 '112601938',
 '100734803',
 '60024541',
 '60015183',
 '60106630',
 '105616644',
 '105605986',
 '60031902',
 '114363017',
 '109346092',
 '60259128',
 '60024705',
 '112601927',
 '118648220',
 '100387916',
 '108988499',
 '108418372',
 '60073581',
 '126849216',
 '60012867',
 '60014502',
 '60014683',
 '128074794',
 '60001224',
 '124443444',
 '60002018',
 '60190678',
 '116657708',
 '60004156',
 '60085748',
 '60273737',
 '60085927',
 '108958739',
 '60017838',
 '60033331',
 '60011132',
 '60027550',
 '101496930',
 '60033403',
 '60007268',
 '107273918',
 '60211748',
 '109899455',
 '60019595',
 '122513521',
 '60030807',
 '113022465',
 '113166407',
 '123787231',
 '60031004',
 '60026617',
 '60016605',
 '60072749',
 '60012359',
 '120376185',
 '60084450',
 '60025252',
 '60031138',
 '102005793',
 '116628164',
 '60023279',
 '60069739',
 '60029515',
 '60101002',
 '60136546',
 '123864806',
 '60068548',
 '60118095',
 '128120398',
 '60071706',
 '123198682',
 '60123531',
 '100561749',
 '100384606',
 '60118868',
 '60070100',
 '60027671',
 '60123120',
 '113733514',
 '60084916',
 '101147226',
 '101012860',
 '60069985',
 '60123782',
 '123323860',
 '60032819',
 '115171873',
 '60032524',
 '60026053',
 '109626301',
 '100315819',
 '112900418',
 '60004256',
 '60104663',
 '106958554',
 '60010591',
 '117819438',
 '60005397',
 '60011170',
 '60002330',
 '60103683',
 '60069980',
 '113775872',
 '60104438',
 '60072699',
 '60007903',
 '60003662',
 '60015576',
 '107106317',
 '60015913',
 '60010971',
 '60027075',
 '60032838',
 '60005421',
 '60104405',
 '60026115',
 '119068671',
 '60031848',
 '60031905',
 '60015833',
 '60025234',
 '60026311',
 '60011774',
 '105413920',
 '100478792',
 '60029472',
 '60108276',
 '60000460',
 '60026434',
 '126636665',
 '60068576',
 '60025059',
 '114757928',
 '60090002',
 '60070023',
 '60029873',
 '101650229',
 '60102227',
 '122507104',
 '127712705',
 '60019499',
 '60111763',
 '115879353',
 '60106479',
 '112728527',
 '60028677',
 '125778303',
 '60019140',
 '60009024',
 '60007155',
 '60026810',
 '127347206',
 '107842973',
 '112912074',
 '60022886',
 '101889919',
 '107122203',
 '60092441',
 '60029833',
 '121362049',
 '60013703',
 '60033490',
 '60014836',
 '60006164',
 '60079129',
 '100451283',
 '60027485',
 '60032577',
 '100453319',
 '60028192',
 '60083127',
 '128463131',
 '60012992',
 '60002959',
 '109626010',
 '113597931',
 '60243126',
 '106441013',
 '60019012',
 '100400997',
 '126636164',
 '60015543',
 '125549351',
 '60013608',
 '101027730',
 '60031218',
 '60029157',
 '112510242',
 '60121355',
 '60014655',
 '60094293',
 '118688090',
 '60001769',
 '110214482',
 '60104575',
 '60002484',
 '123265764',
 '60019311',
 '60021600',
 '112207369',
 '60016104',
 '60105773',
 '60158037',
 '60068680',
 '60272374',
 '60112014',
 '122506417',
 '105492695',
 '109298418',
 '60013227',
 '101114027',
 '60073817',
 '100532618',
 '102015712',
 '125996347',
 '60000961',
 '60010998',
 '60012581',
 '60090096',
 '126985401',
 '112095925',
 '100570314',
 '114582642',
 '60029473',
 '60001317',
 '60021285',
 '123864922',
 '107933186',
 '60108110',
 '60018258',
 '107106790',
 '127918266',
 '100839730',
 '60009189',
 '101869829',
 '60022695',
 '112353218',
 '100335013',
 '60004248',
 '113574604',
 '60003892',
 '60021587',
 '60023609',
 '60023077',
 '114128452',
 '60106222',
 '60031159',
 '60120889',
 '113149851',
 '60020273',
 '100821746',
 '60024574',
 '60104311',
 '60007912',
 '128230851',
 '100552353',
 '101596221',
 '60029616',
 '60115086',
 '60026497',
 '114218035',
 '60083671',
 '126829018',
 '60019029',
 '60011394',
 '60236880',
 '60216472',
 '60026117',
 '100499087',
 '60006514',
 '127805194',
 '117742581',
 '60108278',
 '60099166',
 '112595848',
 '60014959',
 '127186345',
 '112541255',
 '60014809',
 '100565557',
 '122118355',
 '60119067',
 '117025905',
 '101942634',
 '60073468',
 '60011047',
 '60013051',
 '60105635',
 '126504646',
 '115293926',
 '60020210',
 '60117560',
 '60253097',
 '105184720',
 '60018179',
 '60105550',
 '112963756',
 '113762968',
 '60020585',
 '60006771',
 '60018917',
 '124640230',
 '60113483',
 '112587370',
 '101542988',
 '60110597',
 '60003767',
 '60032437',
 '60268191',
 '60026695',
 '112804839',
 '107283611',
 '60021439',
 '60008706',
 '126390264',
 '60016041',
 '60032116',
 '112779825',
 '60105847',
 '115904987',
 '60027158',
 '60117369',
 '121377935',
 '60025659',
 '60003878',
 '60008953',
 '120096957',
 '123864755',
 '60005081',
 '60006221',
 '60002512',
 '100433158',
 '101758258',
 '60085506',
 '101320010',
 '113019142',
 '60013614',
 '60072562',
 '60137829',
 '60030856',
 '101344572',
 '60028333',
 '60024724',
 '60074326',
 '60032468',
 '60108464',
 '60010188',
 '60030718',
 '60108055',
 '60004261',
 '113401704',
 '102073163',
 '60014652',
 '128023315',
 '60024417',
 '60017041',
 '100416963',
 '108405976',
 '60024569',
 '60030506',
 '60004718',
 '60002442',
 '60093675',
 '60108488',
 '124400726',
 '60000679',
 '101233223',
 '119152003',
 '60009543',
 '60011339',
 '60012603',
 '60108893',
 '114545083',
 '60025997',
 '60108633',
 '60015661',
 '101271934',
 '113152229',
 '109865326',
 '60031624',
 '113264067',
 '60106985',
 '60025751',
 '60015881',
 '100888170',
 '60084651',
 '60013369',
 '127659217',
 '102019951',
 '60013551',
 '60013883',
 '60031098',
 '60014596',
 '60020649',
 '110816829',
 '60020204',
 '60194052',
 '123569669',
 '100490223',
 '60068616',
 '101635828',
 '108408933',
 '113528003',
 '60030100',
 '60009647',
 '60109548',
 '101285715',
 '60071577',
 '60022367',
 '100322096',
 '112979466',
 '60029659',
 '60104630',
 '106020580',
 '101976359',
 '100706491',
 '60002337',
 '60085557',
 '117500077',
 '128987859',
 '60027331',
 '106379336',
 '60116160',
 '60104305',
 '100461030',
 '60025757',
 '112488137',
 '108958508',
 '60096199',
 '100639371',
 '60119318',
 '60027229',
 '60138408',
 '105589976',
 '60002356',
 '101040316',
 '128355343',
 '60006461',
 '109088327',
 '60000358',
 '60002214',
 '60028590',
 '100459170',
 '60031430',
 '118618047',
 '60009057',
 '101947660',
 '60005120',
 '60031155',
 '60113884',
 '113483284',
 '100421409',
 '121575417',
 '60011976',
 '60105915',
 '116778053',
 '60113392',
 '60102356',
 '112726938',
 '117522117',
 '106684956',
 '129151860',
 '60027814',
 '60102657',
 '60020565',
 '60104698',
 '60274820',
 '60006455',
 '60022028',
 '125159942',
 '60000867',
 '60000799',
 '100671635',
 '122508460',
 '125159818',
 '60117390',
 '60006790',
 '60069081',
 '60023008',
 '60085212',
 '60023654',
 '100437209',
 '60008132',
 '60014338',
 '100890489',
 '125778961',
 '60001340',
 '128656338',
 '60011533',
 '60029278',
 '60017263',
 '60103673',
 '60119937',
 '128274688',
 '60095610',
 '60001576',
 '60010526',
 '60005429',
 '113582880',
 '101565389',
 '108301672',
 '100337305',
 '60064058',
 '105793122',
 '124366281',
 '60012838',
 '108304156',
 '123346306',
 '60019991',
 '60009470',
 '60006046',
 '60098861',
 '106195169',
 '101114273',
 '112891548',
 '60019598',
 '60004783',
 '126996017',
 '112888715',
 '112962422',
 '116198981',
 '60016246',
 '60097100',
 '60103517',
 '60085060',
 '106055058',
 '60008872',
 '60011069',
 '60105080',
 '113910789',
 '60006240',
 '60023571',
 '124205236',
 '121573106',
 '60000135',
 '100455023',
 '60138963',
 '123865537',
 '60105651',
 '115813927',
 '60013789',
 '116199095',
 '60070791',
 '60024739',
 '123199267',
 '118601096',
 '60021508',
 '60011931',
 '124643637',
 '60028799',
 '60172570',
 '105477579',
 '126828424',
 '60028284',
 '60082819',
 '120334699',
 '123435829',
 '60072054',
 '60110740',
 '60086312',
 '126373434',
 '123840911',
 '121290451',
 '60018446',
 '60006424',
 '117689161',
 '106606811',
 '114535571',
 '60092260',
 '60095034',
 '60017849',
 '60073709',
 '60005597',
 '60031536',
 '60025167',
 '113856153',
 '60028174',
 '60101364',
 '60010237',
 '101481310',
 '60022084',
 '60023137',
 '60004630',
 '60003594',
 '60231076',
 '60010413',
 '60010513',
 '60021023',
 '60271626',
 '125778311',
 '101333657',
 '110078781',
 '60015530',
 '100387352',
 '60027947',
 '60073372',
 '60029392',
 '101592709',
 '60032949',
 '60104230',
 '60092005',
 '60073785',
 '122066232',
 '60002787',
 '60029082',
 '60029346',
 '60008293',
 '60104222',
 '106379085',
 '113510744',
 '128305733',
 '60009222',
 '113782363',
 '60020828',
 '60025187',
 '100451732',
 '60122766',
 '60030409',
 '114380143',
 '60113308',
 '100339717',
 '60030354',
 '100769306',
 '100495581',
 '60105237',
 '60072265',
 '60012018',
 '60014117',
 '60025225',
 '60109878',
 '60024993',
 '60025500',
 '128664260',
 '60159363',
 '60027949',
 '60157957',
 '128448859',
 '60029116',
 '60006299',
 '109208414',
 '60023477',
 '60006183',
 '120798937',
 '110125338',
 '109878866',
 '60015356',
 '106235780',
 '60021255',
 '117440688',
 '60108266',
 '119076207',
 '109863442',
 '60010756',
 '60014070',
 '60008176',
 '60004960',
 '60022417',
 '60087273',
 '122507151',
 '60015864',
 '122910490',
 '119804500',
 '60106924',
 '123192924',
 '60042526',
 '108738816',
 '60016437',
 '127303393',
 '116878576',
 '123341583',
 '60001403',
 '60103628',
 '100857551',
 '114721429',
 '60007328',
 '60108071',
 '60025200',
 '60022525',
 '60019000',
 '124903813',
 '123361923',
 '60006320',
 '107343858',
 '121290468',
 '60027757',
 '101921670',
 '60027290',
 '60092493',
 ...}

In [5]:
bioscience_bibliography.afid.apply(pd.Series).iloc[:,0].value_counts(normalize = True)

60004179     0.019211
60006711     0.018427
60069097     0.017381
60009037     0.010716
60016296     0.009888
               ...
60031447     0.000044
106536368    0.000044
60045954     0.000044
112895248    0.000044
115789797    0.000044
Name: 0, Length: 4775, dtype: float64

In [45]:
scopus.AffiliationRetrieval(60007202).__dir__()

['_view',
 '_refresh',
 '_cache_file_path',
 '_mdate',
 '_json',
 '_profile',
 '__module__',
 'address',
 'affiliation_name',
 'author_count',
 'city',
 'country',
 'date_created',
 'document_count',
 'eid',
 'identifier',
 'name_variants',
 'org_domain',
 'org_type',
 'org_URL',
 'postal_code',
 'scopus_affiliation_link',
 'self_link',
 'search_link',
 'state',
 'status',
 'sort_name',
 'url',
 '__init__',
 '__str__',
 '__doc__',
 'get_cache_file_age',
 'get_cache_file_mdate',
 'get_key_remaining_quota',
 'get_key_reset_time',
 '__dict__',
 '__weakref__',
 '__repr__',
 '__hash__',
 '__getattribute__',
 '__setattr__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__new__',
 '__reduce_ex__',
 '__reduce__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [6]:
scopus.AffiliationRetrieval(60004179)._profile

{'@affiliation-id': '60004179',
 'status': 'update',
 'date-created': {'@day': '02', '@month': '02', '@year': '2008'},
 'preferred-name': {'@source': 'internal-ani',
  '$': 'NASA Ames Research Center'},
 'sort-name': 'NASA Ames Research Center',
 'name-variant': [{'@doc-count': '29404',
   '@source': 'internal-ani',
   '$': 'Nasa Ames Research Center'},
  {'@doc-count': '3303',
   '@source': 'internal-ani',
   '$': 'Ames Research Center'},
  {'@doc-count': '1919',
   '@source': 'internal-ani',
   '$': 'Nasa-ames Research Center'},
  {'@doc-count': '1062', '@source': 'internal-ani', '$': 'Nasa'},
  {'@doc-count': '841',
   '@source': 'internal-ani',
   '$': 'Nasa Ames Research Cent'},
  {'@doc-count': '656',
   '@source': 'internal-ani',
   '$': 'Nasa/ames Research Center'},
  {'@doc-count': '642', '@source': 'internal-ani', '$': 'Ames Research Cent'},
  {'@doc-count': '367', '@source': 'internal-ani', '$': 'Nasa Ames'},
  {'@doc-count': '317', '@source': 'internal-ani', '$': 'Nasa Research Park'},
  {'@doc-count': '259',
   '@source': 'internal-ani',
   '$': 'National Aeronautics And Space Administration'}],
 'address': {'@country': 'usa',
  'city': 'Moffett Field',
  'state': 'CA',
  'postal-code': '94035',
  'country': 'United States'},
 'org-type': 'resi',
 'org-domain': 'nasa.gov',
 'org-URL': 'http://www.nasa.gov/centers/ames/home/index.html'}

In [25]:
pd.DataFrame(scopus.AuthorRetrieval(7004212771).affiliation_history)

,id,parent,type,relationship,afdispname,preferred_name,parent_preferred_name,country_code,country,address_part,city,state,postal_code,org_domain,org_URL
0,110785688,60027950.0,dept,author,None,Department of Chemical Engineering,Carnegie Mellon University,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
1,60027950,NaN,parent,author,None,Carnegie Mellon University,None,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
2,113587821,60027950.0,dept,author,None,Department of Mechanical Engineering,Carnegie Mellon University,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
3,60090776,NaN,parent,author,None,"National Energy Technology Laboratory, Pittsburgh",None,usa,United States,626 Cochrans Mill Road,Pittsburgh,PA,15236-0940,netl.doe.gov,https://netl.doe.gov/
4,113613418,60027950.0,dept,author,None,Department of Materials Science and Engineering,Carnegie Mellon University,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
5,109531166,60027950.0,dept,author,None,Department of Chemical Engineering,Carnegie Mellon University,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
6,108790916,60027950.0,dept,author,None,Department of Chemical Engineering,Carnegie Mellon University,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
7,108336146,60027950.0,dept,author,None,Department of Chemical Engineering,Carnegie Mellon University,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
8,105243609,60023143.0,dept,author,None,Department of Chemistry,Tufts University,usa,United States,419 Boston Avenue,Medford,MA,02155-5801,tufts.edu,https://www.tufts.edu/
9,104415945,60027950.0,dept,author,None,Department of Chemical Engineering,Carnegie Mellon University,usa,United States,5000 Forbes Avenue,Pittsburgh,PA,15213-3890,cmu.edu,https://www.cmu.edu/
10,60008644,NaN,parent,author,None,Fritz Haber Institute of the Max Planck Society,None,deu,Germany,Faradayweg 4-6,Berlin,None,14195,fhi.mpg.de,https://www.fhi.mpg.de/
11,100258138,60023004.0,dept,author,None,Department of Chemical Engineering,University of Delaware,usa,United States,210 South College Ave.,Newark,DE,19716-5200,udel.edu,http://www.udel.edu/
12,113197261,60023004.0,dept,author,None,Department of Chemical Engineering,University of Delaware,usa,United States,210 South College Ave.,Newark,DE,19716-5200,udel.edu,http://www.udel.edu/
13,112570754,60023004.0,dept,author,None,Department of Chemical Engineering,University of Delaware,usa,United States,210 South College Ave.,Newark,DE,19716-5200,udel.edu,http://www.udel.edu/
14,104168124,60023004.0,dept,author,None,Department of Materials Science and Engineering,University of Delaware,usa,United States,210 South College Ave.,Newark,DE,19716-5200,udel.edu,http://www.udel.edu/
15,112898474,60004923.0,dept,author,None,Department of Chemistry,NC State University,usa,United States,None,Raleigh,NC,27695-0001,ncsu.edu,https://www.ncsu.edu/

In [22]:
bioscience_bibliography = pd.read_csv('bioscience_bibliography')
biolists = bioscience_bibliography.afid.dropna().str.split(';')
numpy_list = biolists.to_numpy()
flat_lst = [item for sublist in numpy_list if sublist is not None for item in sublist]
# unique_afids = list(set(flat_lst))
unique_afids = [int(x) for x in flat_lst]
unique_afids

[60170182,
 60072546,
 60031581,
 60027272,
 60014340,
 60012708,
 60011019,
 60006288,
 60004179,
 60003892,
 60000221,
 129393708,
 129393671,
 128944298,
 127131603,
 124841290,
 119559805,
 60136210,
 60073837,
 60028039,
 60030637,
 60019616,
 60001439,
 60000481,
 60007202,
 113582880,
 60011976,
 128131936,
 121595840,
 115293926,
 60032991,
 60027272,
 60017293,
 60172343,
 60017293,
 60017293,
 60105942,
 60000964,
 60208589,
 60122734,
 60094055,
 60009358,
 115043608,
 60031159,
 60019544,
 60003763,
 60025038,
 124841290,
 60019611,
 60077190,
 60029681,
 60028717,
 60022457,
 60017246,
 60012556,
 60005881,
 60002238,
 60002128,
 60024324,
 60002746,
 60002243,
 60019586,
 60012464,
 60007798,
 60000765,
 60170182,
 60162625,
 60106381,
 60012708,
 60011460,
 60006222,
 60004636,
 60004179,
 128664260,
 101951639,
 60172345,
 60003771,
 60002798,
 125643328,
 60111154,
 60008293,
 60007798,
 60069097,
 60003172,
 60032006,
 60025038,
 60009507,
 60008293,
 60028717,
 60012708,
 60006341,
 127967806,
 124841290,
 100340341,
 60117484,
 60030622,
 60009037,
 60000874,
 60075528,
 60017604,
 127577982,
 119841127,
 60027272,
 60000221,
 127881449,
 60102422,
 60009860,
 60032179,
 60031581,
 60029311,
 60009512,
 60007174,
 60138955,
 60116111,
 60026993,
 60022195,
 60016173,
 60016069,
 60015543,
 60014789,
 60011048,
 60007103,
 60003500,
 60001117,
 126535561,
 121802757,
 116988326,
 60017293,
 121522075,
 60025474,
 60032442,
 128576188,
 60105804,
 60007249,
 60004346,
 60008877,
 60108877,
 60019987,
 60071237,
 60024825,
 60014204,
 100377630,
 60031806,
 60025804,
 60011019,
 60001416,
 60000221,
 60027272,
 60025589,
 60001524,
 60077233,
 60019647,
 60031159,
 60012556,
 60007762,
 60000291,
 60000874,
 60073807,
 60024353,
 60021199,
 60010164,
 114749910,
 60011976,
 121595840,
 118836910,
 60001673,
 109504270,
 60002306,
 60019141,
 60002494,
 60111918,
 60068520,
 60030074,
 60027509,
 60025637,
 60021902,
 60008734,
 60008293,
 60007798,
 127083720,
 107137889,
 60025038,
 60014439,
 124841290,
 60172343,
 60010348,
 60003771,
 60019722,
 60069097,
 60017592,
 60019722,
 60013435,
 60007249,
 60121356,
 60025038,
 60007174,
 124841290,
 60121355,
 60031706,
 60025038,
 60020547,
 60014439,
 60013959,
 60012708,
 60007174,
 124841678,
 124841290,
 114180331,
 60012708,
 124841290,
 60023345,
 60014097,
 60099274,
 60025417,
 60024825,
 60014204,
 60017293,
 60011976,
 121595840,
 60031204,
 60026161,
 60007740,
 60005152,
 60001525,
 60000102,
 100791139,
 60019163,
 60012708,
 60007567,
 60025778,
 60011604,
 60023857,
 127907986,
 60077335,
 60031204,
 60000854,
 60025038,
 60023317,
 60014439,
 60002634,
 124841290,
 60086320,
 60007798,
 60007801,
 60030188,
 60028677,
 60007183,
 60030188,
 60028677,
 60015875,
 60007798,
 60007183,
 60175926,
 60070112,
 60068520,
 60030074,
 60021902,
 60007798,
 60002476,
 118072216,
 60012070,
 60000891,
 60029398,
 60027165,
 60019656,
 60006288,
 60089742,
 60084072,
 60031828,
 60019991,
 60016849,
 60274377,
 60026851,
 60009982,
 60007997,
 60005455,
 60002746,
 60012708,
 60007801,
 60006711,
 60004179,
 60021381,
 60012708,
 60007801,
 60006711,
 60004179,
 60015815,
 60025038,
 60013959,
 113465606,
 125778600,
 125778303,
 120861505,
 125540342,
 101259279,
 60017592,
 60121648,
 60031810,
 60020680,
 125295234,
 60072358,
 60031226,
 60029183,
 60027272,
 60023539,
 60022195,
 60021311,
 60015150,
 60012345,
 60011976,
 60003615,
 60001439,
 60009037,
 60029398,
 60027165,
 60023256,
 60012162,
 60007592,
 60007183,
 60006288,
 60004718,
 60004179,
 60012708,
 60004179,
 60002442,
 60008555,
 60004305,
 60006191,
 128448859,
 60031624,
 60026553,
 60002746,
 60001522,
 60117886,
 60002995,
 123865449,
 122581155,
 60015815,
 60019722,
 60007798,
 60104446,
 60027085,
 123580630,
 60030188,
 60028677,
 60007798,
 60007183,
 60002306,
 112819770,
 60012162,
 60028872,
 60001524,
 121658461,
 60118022,
 60109225,
 60071301,
 60068581,
 60033316,
 60025858,
 60012937,
 60002612,
 107933186,
 121573106,
 60012708,
 60008950,
 60029470,
 60019544,
 60003763,
 60018394,
 60009037,
 120265600,
 119075370,
 60017592,
 60029398,
 60028218,
 60016296,
 60006288,
 60002442,
 60029398,
 60027165,
 60006288,
 60004179,
 60031159,
 60007989,
 122507402,
 60029398,
 60027165,
 60023256,
 60012162,
 60007592,
 60007183,
 60006288,
 60004718,
 60004179,
 60117993,
 60050715,
 60030718,
 60030245,
 60021859,
 60021763,
 60019816,
 60013959,
 60004956,
 60004179,
 126828794,
 60019987,
 60106421,
 60006288,
 60002442,
 60029398,
 60027165,
 60019656,
 60006288,
 60031828,
 60007801,
 60268770,
 60264860,
 60064058,
 60059937,
 60086357,
 60029195,
 60012442,
 60002636,
 117869751,
 100821746,
 60009037,
 60003892,
 60031581,
 60029311,
 60009037,
 60071901,
 109673673,
 60009037,
 60175926,
 60068520,
 60031159,
 60021902,
 60014814,
 60007798,
 60114536,
 60006711,
 60000854,
 60009982,
 60027509,
 60007798,
 60004179,
 60028284,
 60022919,
 60022462,
 60013789,
 60015815,
 60024324,
 60023222,
 60021918,
 60017672,
 60015277,
 60002245,
 60031204,
 60000221,
 60027509,
 60007798,
 60006876,
 60004179,
 60028333,
 60024642,
 60008950,
 60010307,
 60000673,
 60019722,
 60003467,
 60004917,
 60159698,
 60025812,
 60016280,
 60000521,
 60030318,
 60024876,
 113501653,
 100639371,
 60103523,
 60029608,
 60029322,
 60025278,
 60021170,
 60014277,
 60013625,
 60012820,
 60011040,
 60010896,
 60003970,
 114674904,
 60162625,
 60122052,
 60030988,
 60028637,
 60019611,
 60162625,
 60004636,
 60027550,
 101317274,
 60015815,
 60170182,
 60010144,
 60032166,
 60018965,
 60017705,
 60013551,
 60086357,
 60029195,
 60001576,
 60028872,
 60017016,
 60011779,
 60004354,
 60021252,
 60014344,
 60031437,
 60027090,
 60025534,
 100453152,
 113685902,
 60007801,
 60004179,
 60009024,
 60019722,
 113865370,
 60021285,
 60006711,
 60010065,
 60009037,
 60007798,
 114536358,
 114535326,
 101566922,
 60208580,
 60015815,
 60007798,
 60005811,
 60031204,
 60004179,
 60021285,
 109666609,
 60028465,
 60015815,
 60032166,
 60025993,
 112335945,
 60013959,
 60007798,
 60028629,
 60024941,
 60013959,
 60013791,
 60012113,
 60011460,
 60007174,
 60004876,
 60004179,
 60002476,
 113259311,
 60243392,
 60003500,
 60001681,
 110816335,
 110815284,
 60059360,
 60017815,
 60015881,
 60006314,
 60004443,
 60031204,
 60009254,
 60021381,
 60006711,
 60006711,
 106055058,
 60025450,
 60022659,
 60014612,
 60028465,
 60000221,
 113781812,
 60026097,
 60025993,
 60011779,
 112335945,
 60068865,
 60012317,
 100917888,
 60093276,
 60013959,
 60006711,
 100340676,
 60029747,
 60020469,
 60028465,
 120692090,
 60011779,
 60006711,
 60004179,
 60109272,
 60066812,
 100536946,
 60031828,
 60025209,
 60002442,
 60120889,
 60031216,
 60029470,
 60017989,
 60017246,
 60006711,
 110545699,
 60007776,
 107723288,
 60015815,
 60007592,
 60069716,
 60027173,
 60012370,
 60033150,
 60000765,
 101981753,
 60022956,
 60115446,
 108094750,
 60021381,
 60006711,
 113760341,
 101955447,
 60005837,
 60001422,
 60019722,
 60000305,
 60024724,
 60019732,
 108958739,
 108958199,
 108958050,
 60021285,
 60028483,
 60030162,
 60029278,
 60025668,
 60028590,
 60015881,
 60013738,
 60007248,
 60017777,
 60026717,
 60031828,
 60025209,
 60002442,
 60004179,
 113591528,
 60021285,
 123196943,
 112677389,
 60025450,
 123196943,
 112677389,
 60031204,
 60020204,
 60010526,
 60006337,
 60024642,
 60016296,
 60006711,
 60072343,
 60025310,
 60023066,
 60012944,
 60012113,
 60007798,
 60001046,
 60000762,
 60017848,
 60021285,
 60004179,
 123196634,
 123196437,
 60014965,
 60004179,
 60001769,
 123199636,
 123196437,
 60009037,
 112730558,
 60095456,
 60270122,
 60107489,
 60014256,
 60011047,
 60000809,
 105472950,
 100815867,
 60011779,
 60002442,
 60015941,
 60013959,
 60010526,
 60031159,
 60026161,
 60015941,
 60013959,
 60010526,
 60013959,
 60012213,
 100830872,
 60021285,
 60021192,
 60028465,
 60004179,
 60103882,
 60019722,
 100440257,
 100344130,
 60012113,
 60010884,
 60007248,
 60016653,
 105605371,
 60012708,
 60007478,
 60010401,
 60005286,
 60002442,
 60077641,
 60013959,
 60011779,
 60014439,
 60121355,
 60029472,
 60033359,
 60021097,
 60015875,
 60007798,
 60013959,
 60010526,
 60004179,
 60028465,
 60004179,
 60027090,
 60011373,
 60016309,
 60020547,
 60009804,
 60006711,
 60000745,
 116706905,
 101869829,
 60009254,
 60059360,
 60019967,
 60015913,
 60001170,
 60104230,
 100368341,
 60030931,
 60021918,
 60070180,
 60009037,
 60004179,
 60003500,
 60005837,
 101560777,
 60008740,
 60009254,
 60009254,
 123192287,
 60009254,
 60009254,
 123192287,
 60009254,
 60033316,
 60031159,
 60019984,
 100433778,
 60032781,
 60010526,
 60006711,
 60033316,
 60031159,
 100433778,
 60033316,
 60029398,
 123193255,
 123193165,
 60031204,
 60000221,
 60031591,
 60004179,
 60027090,
 60006711,
 60003500,
 60013959,
 60015178,
 60015875,
 60009254,
 60032211,
 60033331,
 60007798,
 60009037,
 60006832,
 60004179,
 60000964,
 60103882,
 60015138,
 60031204,
 60001241,
 60033331,
 60000221,
 60031813,
 60010934,
 60009254,
 60006711,
 60030821,
 60004923,
 60030821,
 60022195,
 60013959,
 60004179,
 101178245,
 60009254,
 60006711,
 60031591,
 60004179,
 60028465,
 60011779,
 60025450,
 60004179,
 113577454,
 60119423,
 60002959,
 60001439,
 105640969,
 60016173,
 60027392,
 60027030,
 60013959,
 60006711,
 60002959,
 60002441,
 60022990,
 60033331,
 60000221,
 60033331,
 60000221,
 60022990,
 60026730,
 60075278,
 60031888,
 60007478,
 60004179,
 60009037,
 60004179,
 123194449,
 60004179,
 60009254,
 60006711,
 60030821,
 60030821,
 60004179,
 60006711,
 60002959,
 60031706,
 60030821,
 60013959,
 60069747,
 60025063,
 60030821,
 60030821,
 60006711,
 60002959,
 60008293,
 60032262,
 60006711,
 101760804,
 100580904,
 100510961,
 60086242,
 60030821,
 60010526,
 60006711,
 60000705,
 60030821,
 60013959,
 60013682,
 60030821,
 60030821,
 60102518,
 60102518,
 60004179,
 60002959,
 60002442,
 123199044,
 60004179,
 60030821,
 60030821,
 60006711,
 60004179,
 60002959,
 60006711,
 60002959,
 60005837,
 60004179,
 60002959,
 123196486,
 123196460,
 60004179,
 60010065,
 60119141,
 60003500,
 60119141,
 60006711,
 60032262,
 60000221,
 60030821,
 60027392,
 60027392,
 60004179,
 60030821,
 60016296,
 60002959,
 60030821,
 60006221,
 60003625,
 60000854,
 60014569,
 60007248,
 60003122,
 60007776,
 123197990,
 60004179,
 60007776,
 60030821,
 60006711,
 60002959,
 60030821,
 60006711,
 122119409,
 60031159,
 60022225,
 60071768,
 60027550,
 60027090,
 60024266,
 60018319,
 60016296,
 60013346,
 60009037,
 120548074,
 115470789,
 105478704,
 102011146,
 101986903,
 101930985,
 60004179,
 60015815,
 100691551,
 100929069,
 60016296,
 106628795,
 100950466,
 100929069,
 100529335,
 60016296,
 60103882,
 60031204,
 60013894,
 60031159,
 60007248,
 60033420,
 60004179,
 60016296,
 60011477,
 60004179,
 100398149,
 60031159,
 60029398,
 60069097,
 101569384,
 60006337,
 106790879,
 60006711,
 100398149,
 100398149,
 60030821,
 115869751,
 60029398,
 60013402,
 60000854,
 60000854,
 100430342,
 60010785,
 60015623,
 60123782,
 60106017,
 60105371,
 60031126,
 ...]

In [27]:
from collections import Counter
df = pd.DataFrame(Counter(unique_afids).most_common(1000))
df['affilname'] = df.apply(lambda x: scopus.AffiliationRetrieval(x[0], subscriber='TRUE', view='STANDARD').affiliation_name, axis=1)
df
df.to_excel('affiliation_count.xlsx')

## Affiliation

In [24]:
pd.DataFrame(Counter(unique_afids).most_common(500))

            0     1
0    60004179  1345
1    60006711  1173
2    60009037   836
3    60007798   790
4    60069097   506
..        ...   ...
495  60001970    21
496  60022558    21
497  60022020    21
498  60098668    21
499  60000677    21

[500 rows x 2 columns]

In [ ]:
ab = scopus.AbstractRetrieval("2-s2.0-85068268027", view='FULL')
ab.subject_areas

subject_areas = {}

for author in authors:
    scopus_retrieval = scopus.AbstractRetrieval("2-s2.0-85068268027", view='FULL')

In [7]:
%%time

unique_author_df = pd.DataFrame(index=author_ids, columns=['eids', 'affiliation_history', 'affiliation_current', 'h_index', 'name', 'document_count', 'citation_count'])

for i, author_id in enumerate(author_ids[-100:]):
    # ['h_index', 'affiliation_history', 'affiliation_current', 'eid', 'indexed_name']
    scopus_retrieval = scopus.AuthorRetrieval(author_id, view='ENHANCED')
    unique_author_df.iloc[i, 1] = pd.DataFrame(scopus_retrieval.affiliation_history)
    unique_author_df.iloc[i, 2] = pd.DataFrame(scopus_retrieval.affiliation_current)
    unique_author_df.iloc[i, 0] = scopus_retrieval.eid
    unique_author_df.iloc[i, 3] = scopus_retrieval.h_index
    unique_author_df.iloc[i, 4] = scopus_retrieval.indexed_name
    unique_author_df.iloc[i, 5] = scopus_retrieval.document_count
    unique_author_df.iloc[i, 6] = scopus_retrieval.citation_count
    

unique_author_df

CPU times: user 992 ms, sys: 48.2 ms, total: 1.04 s
Wall time: 37.6 s

,eids,affiliation_history,affiliation_current,h_index,name,document_count,citation_count
0,,,,,,,
8397364800,9-s2.0-35579551400,id parent type relationship...,id parent type relationship afdi...,15,Idkaidek N.,68,717
36664765600,9-s2.0-37020917700,id parent type relationship afdi...,id parent type relationship afdi...,1,Ma S.,1,2
35177423100,9-s2.0-7003664723,id parent type relationshi...,id parent type relationship afdi...,12,Kangas P.,52,698
7005325946,9-s2.0-57251129200,id parent type relationship afdisp...,id parent type relationship afdisp...,1,Schmidt H.,2,2
7409615288,9-s2.0-57209639786,id parent type relationship afdi...,id parent type relationship afdi...,0,Stefanski P.,1,0
...,...,...,...,...,...,...,...
57215592822,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8424066900,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8706064700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8644474800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55584445800,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
%%time

def fetch_author_data(i, author_id, shared_dict):
    scopus_retrieval = scopus.AuthorRetrieval(author_id, view='ENHANCED')
    shared_dict[author_id] = {
        'eids': scopus_retrieval.eid,
        'affiliation_history': pd.DataFrame(scopus_retrieval.affiliation_history),
        'affiliation_current': pd.DataFrame(scopus_retrieval.affiliation_current),
        'h_index': scopus_retrieval.h_index,
        'name': scopus_retrieval.indexed_name,
        'document_count': scopus_retrieval.document_count,
        'citation_count': scopus_retrieval.citation_count
    }

def multiprocess_authors(author_ids):
    unique_author_df = pd.DataFrame(index=author_ids, columns=['eids', 'affiliation_history', 'affiliation_current', 'h_index', 'name', 'document_count', 'citation_count'])
    author_ids_chunk = author_ids[1000:2000]

    manager = multiprocessing.Manager()
    shared_dict = manager.dict()

    processes = []
    for i, author_id in enumerate(author_ids_chunk):
        process = multiprocessing.Process(target=fetch_author_data, args=(i, author_id, shared_dict))
        processes.append(process)
        process.start()

    for process in processes:
        process.join()

    for author_id, result in shared_dict.items():
        unique_author_df.loc[author_id] = [
            result['eids'],
            result['affiliation_history'],
            result['affiliation_current'],
            result['h_index'],
            result['name'],
            result['document_count'],
            result['citation_count']
        ]

    return unique_author_df

unique_author_df = multiprocess_authors(author_ids)
unique_author_df[-100:]